# Generated by Django 3.2.7 on 2021-09-29 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('contact', models.CharField(max_length=15)),
                ('age', models.CharField(max_length=3)),
                ('status', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'employee',
            },
        ),
    ]
