# Generated by Django 3.2.7 on 2021-09-29 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_society_deatils'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Society',
        ),
    ]
