# Generated by Django 3.2.7 on 2021-10-01 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_income_expense_ledger'),
    ]

    operations = [
        migrations.CreateModel(
            name='Income_Expense_Ledger_amount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateOn', models.DateField()),
                ('type', models.CharField(max_length=100)),
                ('amount', models.CharField(max_length=100)),
                ('category_header', models.CharField(max_length=100)),
                ('from_or_to_account', models.CharField(max_length=100)),
                ('transaction_type', models.CharField(max_length=100)),
                ('transaction_details', models.CharField(max_length=100)),
                ('voucherNo_or_invoiceNo', models.CharField(max_length=100)),
                ('opening_balance_cash', models.CharField(max_length=100)),
                ('closing_balance_cash', models.CharField(max_length=100)),
                ('opening_balance_bank', models.CharField(max_length=100)),
                ('closing_balance_bank', models.CharField(max_length=100)),
                ('Entry_date_and_time', models.DateTimeField()),
            ],
        ),
    ]
