# Generated by Django 3.2.7 on 2021-10-01 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_income_expense_ledger_amount'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Income_Expense_Ledger',
        ),
    ]
