# Generated by Django 3.2.7 on 2021-10-01 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_delete_income_expense_ledger'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Income_Expense_Ledger_amount',
            new_name='Income_Expense_Ledger',
        ),
    ]
