# Generated by Django 3.2.7 on 2021-10-05 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_rename_income_expense_ledger_amount_income_expense_ledger'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income_expense_ledger',
            name='amount',
            field=models.FloatField(max_length=100),
        ),
    ]
