# Generated by Django 3.2.7 on 2021-10-05 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_auto_20211005_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balance',
            name='account',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
