# Generated by Django 3.2.7 on 2021-10-05 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_alter_balance_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='income_expense_ledger',
            name='Entry_date_and_time',
        ),
    ]
