# Generated by Django 3.2.7 on 2021-10-06 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_society_deatils1'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Society_deatils1',
            new_name='Society_all_deatils',
        ),
    ]
