# Generated by Django 3.2.7 on 2021-10-13 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_alter_income_expense_ledgervalue_remark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income_expense_ledgervalue',
            name='remark',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
