# Generated by Django 3.2.7 on 2021-10-18 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_alter_income_expense_ledgervalue_remark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income_expense_ledgervalue',
            name='category_header',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
