# Generated by Django 3.2.7 on 2021-10-19 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0025_income_expense_ledgervalue_entry_time'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Income_Expense_Ledger',
        ),
    ]
