# Generated by Django 3.2.7 on 2021-10-19 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0027_delete_employee'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Balance',
        ),
    ]
