# Generated by Django 3.2.7 on 2021-10-21 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0028_delete_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income_expense_ledgervalue',
            name='from_or_to_account',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
