# Generated by Django 3.2.7 on 2021-10-21 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0029_alter_income_expense_ledgervalue_from_or_to_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members_vendor_account',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
