# Generated by Django 3.2.7 on 2021-10-21 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0030_alter_members_vendor_account_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income_expense_ledgervalue',
            name='transaction_details',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
