# Generated by Django 3.2.7 on 2021-10-28 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0032_user_society_deatils'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Society_deatils',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='income_expense_ledgervalue',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/images', verbose_name='image'),
        ),
    ]
