# Generated by Django 3.2.7 on 2021-10-28 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0033_auto_20211028_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income_expense_ledgervalue',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='userinterface/myapp/static/images', verbose_name='image'),
        ),
    ]
