# Generated by Django 3.2.7 on 2021-11-17 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0035_alter_income_expense_ledgervalue_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, max_length=100, null=True)),
                ('type_file', models.FileField(blank=True, null=True, upload_to='filestore/', verbose_name='file')),
            ],
        ),
    ]
