# Generated by Django 3.2.7 on 2021-11-17 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0036_filestore'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileStoreValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, max_length=100, null=True)),
                ('type_file', models.FileField(blank=True, null=True, upload_to='filestore/', verbose_name='file')),
                ('income_Expense_LedgerId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.income_expense_ledgervalue')),
            ],
        ),
    ]
